#!/bin/bash -e

mkdir -p /ipfs
chown ipfs:ipfs /ipfs

export IPFS_PATH=/ipfs

chpst -u ipfs:ipfs /usr/local/bin/ipfs init --empty-repo 2>&1 || true

exec chpst -u ipfs:ipfs /usr/local/bin/ipfs daemon --init --migrate --enable-gc --enable-pubsub-experiment 2>&1
